/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QuanLy;

import BUS.KhachHangBus;
import DAO.KhachHangDAO;
import DTO.KhachHang_DTO;
import Handle.Timeconvert;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class QuanLyKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhachHang
     */
    KhachHangDAO khd = new KhachHangDAO();
    KhachHangBus khb = new KhachHangBus();

    public QuanLyKhachHang() {
        initComponents();
        createButtonGroup();
        showCustomerInTable();

    }

    public void showCustomerInTable() {
        DefaultTableModel model = (DefaultTableModel) TableCustomer.getModel();
        model.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong bảng

        ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
        int soLuongKH = danhSachKhachHang.size();
        for (int i = 0; i < soLuongKH; i++) {
            KhachHang_DTO khachHang = danhSachKhachHang.get(i);
            String maKH = khachHang.getMaKH();
            String tenKH = khachHang.getTenKH();
            String sdt = khachHang.getSdt();
            LocalDate ngaySinh = khachHang.getNgaySinh();
            String diaChi = khachHang.getDiaChi();
            boolean tonTai = khachHang.isTonTai();
            String tinhTrang;
            if (tonTai) {
                tinhTrang = "Còn hoạt động";
            } else {
                tinhTrang = "Đã xóa";
            }
            model.addRow(new Object[]{i + 1, maKH, tenKH, sdt, ngaySinh, diaChi, tinhTrang});
        }
        txtMaKh.setEnabled(false);
    }

    public void createButtonGroup() {
        ButtonGroup arrangeGroup = new ButtonGroup();
        arrangeGroup.add(chkArrangeAZ);
        arrangeGroup.add(chkArrangeZA);
    }

    public void clearAll() {
        txtName.setText("");
        txtNumberPhone.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtName.setEnabled(true);
        txtNgaySinh.setEnabled(true);
        txtMaKh.setText("");
        showCustomerInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCustomer = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumberPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        btnArrange = new javax.swing.JButton();
        chkArrangeAZ = new javax.swing.JRadioButton();
        chkArrangeZA = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaKh = new javax.swing.JTextField();
        txtFindBySDT = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 187, 198));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ KHÁCH HÀNG");

        TableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Ngày sinh", "Địa chỉ", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCustomer);

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bin.png"))); // NOI18N
        btnDelete.setText("XÓA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 255, 204));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/broom.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(255, 255, 0));
        btnFind.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btnFind.setText("TÌM KIẾM");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 255, 0));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADD.png"))); // NOI18N
        btnAdd.setText("THÊM");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 255, 0));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sync.png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnClear)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnFind)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Họ tên");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Số điện thoại");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Ngày sinh");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");

        btnArrange.setBackground(new java.awt.Color(102, 255, 51));
        btnArrange.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnArrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting.png"))); // NOI18N
        btnArrange.setText("SẮP XẾP");
        btnArrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArrangeMouseClicked(evt);
            }
        });

        chkArrangeAZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkArrangeAZ.setText("A - Z");

        chkArrangeZA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkArrangeZA.setText("Z - A");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mã khách hàng");

        txtFindBySDT.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập sdt để tìm kiếm khách hàng"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumberPhone)
                            .addComponent(txtNgaySinh)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtDiaChi))))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnArrange)
                        .addGap(18, 18, 18)
                        .addComponent(chkArrangeAZ)
                        .addGap(18, 18, 18)
                        .addComponent(chkArrangeZA))
                    .addComponent(txtFindBySDT, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnArrange)
                        .addComponent(chkArrangeAZ)
                        .addComponent(chkArrangeZA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindBySDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("Thông tin khác hàng");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String hoTen = txtName.getText();
        String soDT = txtNumberPhone.getText();
        String diaChi = txtDiaChi.getText();
        String ngaySinh = txtNgaySinh.getText().trim();
        if (hoTen.equals("")) {
            JOptionPane.showMessageDialog(null, "Họ tên không được để trống");
            return;
        }
        if (diaChi.equals("")) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống");
            return;
        }
        if (soDT.equals("")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không được để trống");
            return;
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate localDate;
        try {
            localDate = LocalDate.parse(ngaySinh, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ. Định dạng đúng là dd-MM-yyyy.");
            return; // Dừng xử lý tiếp theo
        }
        KhachHangBus khb = new KhachHangBus();
        khb.themKhanhHang(hoTen, localDate, soDT, diaChi, true);
        showCustomerInTable();
        btnClearActionPerformed(null);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String sdt = txtNumberPhone.getText().trim();
        if (sdt.equals("")) {
             JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng để xóa");
            return;
        }
        int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            khb.xoaKhachHang(sdt);
            showCustomerInTable();
            clearAll();
        } else {
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void TableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCustomerMouseClicked
        Timeconvert timeConvert = new Timeconvert();
        if (evt.getClickCount() == 1) { // Đảm bảo rằng đó là một lần click đơn, bạn có thể thay đổi số click cần thiết
            int selectedRow = TableCustomer.getSelectedRow();
            if (selectedRow != -1) {
                String soDT = (String) TableCustomer.getValueAt(selectedRow, 3);
                ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
                int soLuongKH = danhSachKhachHang.size();
                for (int i = 0; i < soLuongKH; i++) {
                    KhachHang_DTO khachHang = danhSachKhachHang.get(i);
                    if (soDT.equals(khachHang.getSdt())) {
                        txtName.setEnabled(false);
                        txtNgaySinh.setEnabled(false);
                        txtMaKh.setEnabled(false);

                        txtName.setText(khachHang.getTenKH());
                        txtNumberPhone.setText(khachHang.getSdt());
                        String ngaySinh = timeConvert.convert(khachHang.getNgaySinh());
                        txtNgaySinh.setText(ngaySinh);
                        txtDiaChi.setText(khachHang.getDiaChi());
                        txtMaKh.setText(khachHang.getMaKH());
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_TableCustomerMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maKH = txtMaKh.getText();
         if (maKH.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng để sửa");
            return;
        }
        String sdt = txtNumberPhone.getText();
        String diaChi = txtDiaChi.getText();
        if (sdt.equals("")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không được để trống");
            return;
        }
        if (diaChi.equals("")) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống");
            return;
        }
        int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn muốn sửa thông tin khách hàng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            khb.suaKhachHang(maKH, sdt, diaChi);
            showCustomerInTable();
            clearAll();
        } else {
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String sdt = txtFindBySDT.getText();
        if (sdt.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập SĐT khách hàng để tìm kiếm thông tin khách hàng!!");
            return;
        }
        KhachHang_DTO khachHang = khb.timKhachHang(null, sdt);
        DefaultTableModel model = (DefaultTableModel) TableCustomer.getModel();
        model.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong bảng 
        String maKH = khachHang.getMaKH();
        String tenKH = khachHang.getTenKH();
        String soDienThoai = khachHang.getSdt();
        LocalDate ngaySinh = khachHang.getNgaySinh();
        String diaChi = khachHang.getDiaChi();
        model.addRow(new Object[]{1, maKH, tenKH, soDienThoai, ngaySinh, diaChi});
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnArrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrangeMouseClicked
        DefaultTableModel model = (DefaultTableModel) TableCustomer.getModel();
        model.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong bảng
        ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();

        // Sắp xếp danh sách theo tenKH bằng cách sử dụng Comparator
        Collections.sort(danhSachKhachHang, new Comparator<KhachHang_DTO>() {
            @Override
            public int compare(KhachHang_DTO kh1, KhachHang_DTO kh2) {
                return kh1.getTenKH().compareTo(kh2.getTenKH());
            }
        });
        int soLuongKH = danhSachKhachHang.size();
        if (chkArrangeAZ.isSelected()) {
            for (int i = 0; i < soLuongKH; i++) {
                KhachHang_DTO khachHang = danhSachKhachHang.get(i);
                String maKH = khachHang.getMaKH();
                String tenKH = khachHang.getTenKH();
                String sdt = khachHang.getSdt();
                model.addRow(new Object[]{i + 1, maKH, tenKH, sdt});
            }
        }
        if (chkArrangeZA.isSelected()) {
            for (int i = soLuongKH - 1; i >= 0; i--) {
                KhachHang_DTO khachHang = danhSachKhachHang.get(i);
                String maKH = khachHang.getMaKH();
                String tenKH = khachHang.getTenKH();
                String sdt = khachHang.getSdt();
                model.addRow(new Object[]{i + 1, maKH, tenKH, sdt});
            }
        }
    }//GEN-LAST:event_btnArrangeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCustomer;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnArrange;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JRadioButton chkArrangeAZ;
    private javax.swing.JRadioButton chkArrangeZA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtFindBySDT;
    private javax.swing.JTextField txtMaKh;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNumberPhone;
    // End of variables declaration//GEN-END:variables
}
