/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QuanLy;

import DAO.KhachHangDAO;
import DTO.KhachHang_DTO;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class QuanLyKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhachHang
     */
    KhachHangDAO khd = new KhachHangDAO();

    public QuanLyKhachHang() {
        initComponents();
        showCustomerInTable();
    }

    public void showCustomerInTable() {
        DefaultTableModel model = (DefaultTableModel) TableCustomer.getModel();
        model.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong bảng

        ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
        int soLuongKH = danhSachKhachHang.size();
        for (int i = 0; i < soLuongKH; i++) {
            KhachHang_DTO khachHang = danhSachKhachHang.get(i);
            String maKH = khachHang.getMaKH();
            String tenKH = khachHang.getTenKH();
            String sdt = khachHang.getSdt();
            boolean tonTai = khachHang.isTonTai();
            String tinhTrang;
            if (tonTai) {
                tinhTrang = "Còn hoạt động";
            } else {
                tinhTrang = "Đã xóa";
            }
            model.addRow(new Object[]{i + 1, maKH, tenKH, sdt, tinhTrang});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCustomer = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnDelCustomer = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnFindCustomer = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumberPhone = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 187, 198));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ KHÁCH HÀNG");

        TableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCustomer);

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btnDelCustomer.setText("Xóa");
        btnDelCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCustomerActionPerformed(evt);
            }
        });

        jButton17.setText("Clear");

        btnEditCustomer.setText("Sửa");

        btnFindCustomer.setText("Tìm kiếm");

        btnAddCustomer.setText("Thêm");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnDelCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnEditCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnFindCustomer)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelCustomer)
                    .addComponent(btnEditCustomer)
                    .addComponent(jButton17)
                    .addComponent(btnFindCustomer)
                    .addComponent(btnAddCustomer))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel5.setText("Họ tên");

        jLabel13.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Thông tin khác hàng");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
        int soLuongKH = danhSachKhachHang.size();
        String name = txtName.getText();
        String numberPhone = txtNumberPhone.getText();
        if (name.isEmpty() || numberPhone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền đủ thông tin!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return; // Không thêm khách hàng nếu thông tin không đủ
        }
        for (int i = 0; i < soLuongKH; i++) {
            KhachHang_DTO kh = danhSachKhachHang.get(i);
            if (numberPhone.equals(kh.getSdt())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại đã được sử dụng", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return; // Không thêm khách hàng nếu trùng sđt
            }
        }
        String numberId = "";
        LocalDate birthday = LocalDate.of(1990, 5, 15);

        KhachHang_DTO khachHangCuoi = danhSachKhachHang.get(soLuongKH - 1);
        if (khachHangCuoi == null) {
            return;
        }
        int maKHInt = Integer.parseInt(khachHangCuoi.getMaKH());
        if (maKHInt < 9) {
            numberId = "000000" + (maKHInt + 1);
        } else if (maKHInt >= 9 && maKHInt < 99) {
            numberId = "00000" + (maKHInt + 1);
        } else if (maKHInt >= 99 && maKHInt < 999) {
            numberId = "0000" + (maKHInt + 1);
        } else if (maKHInt >= 999 && maKHInt < 9999) {
            numberId = "000" + (maKHInt + 1);
        } else if (maKHInt >= 9999 && maKHInt < 99999) {
            numberId = "00" + (maKHInt + 1);
        } else if (maKHInt >= 99999 && maKHInt < 999999) {
            numberId = "0" + (maKHInt + 1);
        }
        KhachHang_DTO newKH = new KhachHang_DTO(numberId, name, birthday, numberPhone, null, true);

        khd.add(newKH);
        showCustomerInTable();
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnDelCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCustomerActionPerformed
        String numberPhone = txtNumberPhone.getText();
        ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
        int soLuongKH = danhSachKhachHang.size();
        for (int i = 0; i < soLuongKH; i++) {
            KhachHang_DTO khachHang = danhSachKhachHang.get(i);
            if (khachHang.getSdt().equals(numberPhone)) {
                khd.delete(khachHang);
                break;
            }
        }
        showCustomerInTable();
    }//GEN-LAST:event_btnDelCustomerActionPerformed

    private void TableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCustomerMouseClicked
        if (evt.getClickCount() == 1) { // Đảm bảo rằng đó là một lần click đơn, bạn có thể thay đổi số click cần thiết
            int selectedRow = TableCustomer.getSelectedRow();
            if (selectedRow != -1) {
                String soDT = (String) TableCustomer.getValueAt(selectedRow, 3);
                ArrayList<KhachHang_DTO> danhSachKhachHang = khd.ReadKhachHang();
                int soLuongKH = danhSachKhachHang.size();
                for (int i = 0; i < soLuongKH; i++) {
                    KhachHang_DTO khachHang = danhSachKhachHang.get(i);
                    if (soDT.equals(khachHang.getSdt())) {
                        txtName.setText(khachHang.getTenKH());
                        txtNumberPhone.setText(khachHang.getSdt());
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_TableCustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCustomer;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDelCustomer;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumberPhone;
    // End of variables declaration//GEN-END:variables
}
