/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QuanLy;
import BUS.ChiTietPhieuNhapBus;
import BUS.NhaCungCapBus;
import BUS.PhieuNhapBus;
import BUS.PhieuYeuCauNhapBus;
import DAO.ChiTietPhieuNhapDAO;
import DAO.PhieuYeuCauNhapDAO;
import DTO.ChiTietPhieuNhap_DTO;
import DTO.PhieuNhap_DTO;
import Handle.Convert;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class ReadPhieuYeuCauNhap extends javax.swing.JPanel {

    private String MaPN;
    ChiTietPhieuNhapBus ctpnBUS = new ChiTietPhieuNhapBus();
    ChiTietPhieuNhapDAO ctpnDAO = new ChiTietPhieuNhapDAO();
    NhaCungCapBus nccBUS = new NhaCungCapBus();
    PhieuYeuCauNhapDAO pycnDAO = new PhieuYeuCauNhapDAO();
    PhieuNhapBus pnBUS = new PhieuNhapBus();
    Convert cv = new Convert();
    public ReadPhieuYeuCauNhap(String mapn) {
        initComponents();

        this.MaPN = mapn;
        showPhieuNhapInTable();
    }

    public void showPhieuNhapInTable() {
        DefaultTableModel model = (DefaultTableModel) tablePhieuYeuCauNhap.getModel();
        model.setRowCount(0);
        ArrayList<ChiTietPhieuNhap_DTO> chiTietPhieuNhap = pycnDAO.searchCTPN(MaPN, null, null, null);
       
        double total = 0;
        
        for (int i = 0; i < chiTietPhieuNhap.size(); i++) {
            ChiTietPhieuNhap_DTO ctpnDTO = chiTietPhieuNhap.get(i);
            String tenNCC = nccBUS.timTenNCC(ctpnDTO.getMaNCC());
            total += ctpnDTO.getTongTienNhap();
            
            model.addRow(new Object[]{ctpnDTO.getMaPhieuNhap(), ctpnDTO.getMaHangNhap(), ctpnDTO.getTenHangNhap(), tenNCC, ctpnDTO.getVAT(), ctpnDTO.getXuatXu(), ctpnDTO.getSoLuong(), ctpnDTO.getDonVi(),  ctpnDTO.getGiaNhap(), ctpnDTO.getTongTienNhap()});
        }
        model.addRow(new Object[]{null, null, null, null, null, null, null, null ,"Tổng:", total});
      
    }

    public String MaPN(String mapn){
        return MaPN= mapn;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuYeuCauNhap = new javax.swing.JTable();
        txtSuaSoLuong = new javax.swing.JTextField();
        txtSuaGiaNhap = new javax.swing.JTextField();
        cbbMaNCC = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        tablePhieuYeuCauNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Mã mặt hàng", "Tên mặt hàng", "Tên NCC", "VAT", "Xuất xứ", "Số lượng", "Đơn vị", "Giá nhập", "Tổng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePhieuYeuCauNhap);

        txtSuaSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa số lượng"));

        txtSuaGiaNhap.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa giá nhập"));

        cbbMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công ty TNHH Nhà Máy Bia HEINEKEN Việt Nam", "Công ty Acecook Việt Nam", "Công ty cung cấp thực phẩm", "FrieslandCampina Việt Nam" }));
        cbbMaNCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Tùy chọn nhà cung cấp"));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updated.png"))); // NOI18N
        btnUpdate.setText("SỬA THÔNG TIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbbMaNCC, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtSuaSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(txtSuaGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuaSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuaGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbMaNCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePhieuYeuCauNhap;
    private javax.swing.JTextField txtSuaGiaNhap;
    private javax.swing.JTextField txtSuaSoLuong;
    // End of variables declaration//GEN-END:variables
}
