/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QuanLy;

import BUS.ChiTietPhieuNhapBus;
import DAO.ChiTietPhieuNhapDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class ReadPhieuYeuCauNhap extends javax.swing.JPanel {

    /**
     * Creates new form ReadPhieuYeuCauNhap
     */
    private String MaPN;
    ChiTietPhieuNhapBus ctpnBUS = new ChiTietPhieuNhapBus();
    ChiTietPhieuNhapDAO ctpnDAO = new ChiTietPhieuNhapDAO();
    public ReadPhieuYeuCauNhap() {
        initComponents();
        showInforPhieuNhapInTable();
    }
    public void showInforPhieuNhapInTable(){
//          DefaultTableModel model = (DefaultTableModel) tablePhieuYeuCauNhap.getModel();
//        model.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong bảng
        System.out.println("Chi tiet phieu nhap ->  " +ctpnDAO.searchCTPN(MaPN, null, null, null)); 
    }
    public String MaPN(String mapn){
        return MaPN= mapn;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuYeuCauNhap = new javax.swing.JTable();
        txtSuaSoLuong = new javax.swing.JTextField();
        txtSuaGiaNhap = new javax.swing.JTextField();
        cbbMaNCC = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();

        tablePhieuYeuCauNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Mã mặt hàng", "Tên mặt hàng", "Tên NCC", "VAT", "Xuất xứ", "Số lượng", "Đơn vị", "Giá nhập", "Tổng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePhieuYeuCauNhap);

        txtSuaSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa số lượng"));

        txtSuaGiaNhap.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa giá nhập"));

        cbbMaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công ty TNHH Nhà Máy Bia HEINEKEN Việt Nam", "Công ty Acecook Việt Nam", "Công ty cung cấp thực phẩm", "FrieslandCampina Việt Nam" }));
        cbbMaNCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Tùy chọn nhà cung cấp"));

        btnUpdate.setText("Sửa thông tin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSuaSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuaGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSuaSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSuaGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbMaNCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePhieuYeuCauNhap;
    private javax.swing.JTextField txtSuaGiaNhap;
    private javax.swing.JTextField txtSuaSoLuong;
    // End of variables declaration//GEN-END:variables
}
